### ISSUE TITLE
Change theme to Lanyon

### ISSUE THREAD

**Issue by akhyarrh** [nectktar/jekyll-boilerplate#7]
https://github.com/poole/lanyon

**Comment by akhyarrh** [comment]
Jekyll now support remote theme

ref: https://github.com/benbalter/jekyll-remote-theme

**Comment by makrufbobob** [comment]
Oit

Pada tanggal Sen, 28 Okt 2019 20.29, M Akhyar Rahman Hidayat <
notifications@github.com> menulis:

**Comment by akhyarrh** [comment]
Haha lulz

**Comment by makrufbobob** [comment]
Dimana posisi ?

Pada tanggal Kam, 31 Okt 2019 02.56, M Akhyar Rahman Hidayat <
notifications@github.com> menulis:

**Comment by akhyarrh** [comment]
Lagi di marabahan no

**Comment by makrufbobob** [comment]
Begawi dimana lut?

Pada tanggal Kam, 31 Okt 2019 14.27, M Akhyar Rahman Hidayat <
notifications@github.com> menulis:
